import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[colors.primary]
background = "0x1c1c1c"
foreground = "0xc5c8c6"

[cursor]
style = "Block"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
decorations = "full"
opacity = 0.9
